disableKinds:
  - taxonomy
theme:
  - scientific-python-hugo-theme/themes/hugo-atom-feed
params:
  colorScheme: auto # can be auto (browser setting), light, or dark
  navColor: blue
  font:
    name: "Lato"
    sizes: [400, 900]
  plausible:
    dataDomain: null
    javaScript: "https://views.scientific-python.org/js/script.js"
