# TODO: Consider renaming this file to "hugo.yaml" in accordance with
# recommendations since v0.109 of Hugo.

# TODO: Consider splitting config into separate files in a "config/"
# directory hierarchy.  See
# <https://gohugo.io/getting-started/configuration/#recursive-parsing>.

disableKinds:
  - taxonomy
theme:
  - scientific-python-hugo-theme/themes/hugo-atom-feed
params:
  colorScheme: auto # can be auto (browser setting), light, or dark
  images:
    - /images/logo.svg
  navColor: blue
  font:
    name: "Lato"
    sizes: [400, 900]
  plausible:
    dataDomain: null
    javaScript: "https://views.scientific-python.org/js/script.js"
