disableKinds:
  - taxonomy
theme:
  - scientific-python-hugo-theme/themes/hugo-atom-feed
params:
  colorScheme: auto # can be auto (browser setting), light, or dark
  images:
    - /images/logo.svg
  navColor: blue
  search: false
  plausible:
    dataDomain: null
    javaScript: "https://views.scientific-python.org/js/script.js"
