[project]
name = "scientific-python-hugo-theme"
version = "0.17rc0.dev0"

[tool.changelist]
# Profiles that are excluded from the contributor list.
ignored_user_logins = ["dependabot[bot]", "pre-commit-ci[bot]", "web-flow"]
