baseURL: "https://theme.scientific-python.org/"
languageCode: "en-us"
title: "Scientific Python Hugo Theme documentation"
theme: scientific-python-hugo-theme
relativeURLs: true
disableKinds: ["taxonomy"]

markup:
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true
    renderHooks:
      link:
        useEmbedded: fallback

params:
  author:
    name: "Scientific Python team"
  description: "Documentation & template site for the Scientific Python Hugo Theme."
  images:
    - /images/logo.svg
  search: true
  navbarlogo:
    image: logo.svg
    text: Scientific Python Hugo Theme
    link: /
  fonts:
    - name: "Lato"
      weights: [400, 900]
  hero:
    title: Scientific Python Theme
    image: logo.svg
    buttontext: Get Started
    buttonlink: /user_guide/getstarted/
  navbar:
    - title: User Guide
      url: /user_guide/
    - title: Shortcodes
      url: /shortcodes/
    - title: Examples
      url: /examples/
    - title: Repository
      url: https://github.com/scientific-python/scientific-python-hugo-theme
      is_external: true
    - title: More
      sublinks:
        - title: Dropdown item
          url: /
        - title: Dropdown item
          url: /
  footer:
    logo: logo.svg
    socialmediatitle: ""
    socialmedia:
      - link: https://github.com/scientific-python/
        icon: github
      - link: https://fosstodon.org/@scientific_python
        icon: mastodon
      - link: https://discuss.scientific-python.org
        icon: discourse
      - link: https://discord.com/invite/vur45CbwMz
        icon: discord
      - link: https://bsky.app/profile/scientific-python.org
        icon: bluesky
      - link: https://linkedin.com/company/scientific-python
        icon: linkedin

    quicklinks:
      column1:
        title: ""
        links:
          - text: About
            link: /about/
          - text: Theme GitHub
            link: https://github.com/scientific-python/scientific-python-hugo-theme
            is_external: true
      column2:
        links:
          - text: Scientific Python Forum
            link: https://discuss.scientific-python.org
            is_external: true
      column3:
        links:
