name: Milestone

on:
  pull_request_target: # zizmor: ignore[dangerous-triggers]
    types:
      - closed
    branches:
      - "main"

jobs:
  milestone_pr:
    name: attach to PR
    if: github.event.pull_request.merged == true
    permissions:
      contents: read
      issues: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: scientific-python/attach-next-milestone-action@c9cfab10ad0c67fed91b01103db26b7f16634639
        with:
          token: ${{ secrets.MILESTONE_LABELER_TOKEN }}
          force: true
